### ISSUE TITLE
Trying to test realtime database.

### ISSUE THREAD

**Issue by shafnaz** [fenix-hub/godot-engine.supabase#37]
Hi @fenix-hub ,
I'm trying to get signals after setting up the subscribe, but with no luck.

![image](https://user-images.githubusercontent.com/37254287/140584030-44a12e1c-8719-4701-8637-59011c3b8d60.png)

Then I just add rows to my table in the app.supabase.io.
I'm not sure if it's connected but I get these output messages:
![image](https://user-images.githubusercontent.com/37254287/140584215-7686147d-f0cb-4f45-b8cf-3da3623d079e.png)

**Comment by fenix-hub** [comment]
Hi @shafnaz 
The Realtime module is working correctly, indeed you are getting a websocket message from the phoenix topic with a status "ok", which means that the connection is alive and you did a successful connection.
I think that you are not getting any update because you have not enabled supabase to send you realtime messages, eventually. 
Check out [this](https://supabase.io/docs/guides/api#managing-realtime)

![image](https://user-images.githubusercontent.com/45271396/140605992-5eab6f2d-fc4d-4c33-9d81-6ae21e2be761.png)
in "Replication", the source column is always pointing to "0 tables" on newly created projects.
Click on the "0 tables" button and enable the tables you want updates from
You can do this while my plugin is still subscribed too, so you can test this out

**Comment by shafnaz** [comment]
Awesome! time to enter real-time gaming.
