### ISSUE TITLE
invalid grant >> email not confirmed

### ISSUE THREAD

**Issue by ShatReal** [fenix-hub/godot-engine.supabase#40]
I followed the instructions and set up the .env file. But when I paste in the test login info, it gives me this error

```
--- Debugging process started ---
Godot Engine v3.4.4.stable.official.419e713a2 - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce MX230/PCIe/SSE2
OpenGL ES Batching: ON
 
invalid_grant >> Email not confirmed
invalid_request >> refresh_token required
 42P01 >> relation "public.todos" does not exist: Null (empty)
```

**Comment by ShatReal** [comment]
This is for the todos demo by the way.

I think I have to set something up on the backend, but I'm not sure what.

**Comment by ShatReal** [comment]
Also, is there a way to upload images to supabase?

**Comment by fenix-hub** [comment]
Hi @ShatReal 
As you can see it first prints out `invalid_grant >> Email not confirmed`, which means that the user you logged in was not verified with email confirmation. If you don't want to, you need to disable this in your supabase instance (through settings)
Then since you are not authorized all requests will fail.
`public.todos` will exist only if you set up the "To Do" tutorial in supabase backend

**Comment by fenix-hub** [comment]
> Also, is there a way to upload images to supabase?
Yes, thorugh Storage
